# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFight = channel.unary_unary(
                '/fighter.agent.v1.AIService/AnalyzeFight',
                request_serializer=ai__service__pb2.AnalyzeFightRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AnalysisResult.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/fighter.agent.v1.AIService/GenerateSummary',
                request_serializer=ai__service__pb2.GenerateSummaryRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SummaryResult.FromString,
                _registered_method=True)
        self.SearchVideos = channel.unary_unary(
                '/fighter.agent.v1.AIService/SearchVideos',
                request_serializer=ai__service__pb2.SearchVideosRequest.SerializeToString,
                response_deserializer=ai__service__pb2.VideosResult.FromString,
                _registered_method=True)
        self.ParseHemagon = channel.unary_unary(
                '/fighter.agent.v1.AIService/ParseHemagon',
                request_serializer=ai__service__pb2.ParseHemagonRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ParseResult.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseHemagon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFight': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFight,
                    request_deserializer=ai__service__pb2.AnalyzeFightRequest.FromString,
                    response_serializer=ai__service__pb2.AnalysisResult.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=ai__service__pb2.GenerateSummaryRequest.FromString,
                    response_serializer=ai__service__pb2.SummaryResult.SerializeToString,
            ),
            'SearchVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVideos,
                    request_deserializer=ai__service__pb2.SearchVideosRequest.FromString,
                    response_serializer=ai__service__pb2.VideosResult.SerializeToString,
            ),
            'ParseHemagon': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseHemagon,
                    request_deserializer=ai__service__pb2.ParseHemagonRequest.FromString,
                    response_serializer=ai__service__pb2.ParseResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fighter.agent.v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fighter.agent.v1.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fighter.agent.v1.AIService/AnalyzeFight',
            ai__service__pb2.AnalyzeFightRequest.SerializeToString,
            ai__service__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fighter.agent.v1.AIService/GenerateSummary',
            ai__service__pb2.GenerateSummaryRequest.SerializeToString,
            ai__service__pb2.SummaryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fighter.agent.v1.AIService/SearchVideos',
            ai__service__pb2.SearchVideosRequest.SerializeToString,
            ai__service__pb2.VideosResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseHemagon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fighter.agent.v1.AIService/ParseHemagon',
            ai__service__pb2.ParseHemagonRequest.SerializeToString,
            ai__service__pb2.ParseResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
